name: 👌PROXY SCAN

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write   # biar bisa push hasil

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Start Scan
        run: bun run ./backend/proxyip.ts

      - name: Commit and Push Result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/mazcekproxy.txt
          git commit -m "Update proxy scan results [skip ci]" || echo "No changes to commit"
          git push origin main
