name: 👌PROXY SCANNER (NodeJS)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # setiap 10 menit

permissions:
  contents: write

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan
      cancel-in-progress: false
    timeout-minutes: 40

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Remove old output
        run: rm -f backend/src/mazcekproxy.txt || true

      - name: Run proxy scanner
        run: node backend/proxy.js

      - name: Show result preview
        run: |
          echo "---- head mazcekproxy.txt ----"
          head -n 30 backend/src/mazcekproxy.txt || true
          echo "---- size ----"
          if [ -f backend/src/mazcekproxy.txt ]; then du -h backend/src/mazcekproxy.txt; else echo "no result file"; fi

      - name: Commit and Push Result
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/src/mazcekproxy.txt || true
          git commit -m "👌UPDATE PROXY" || echo "No changes to commit"
          git push origin main || echo "Push failed"
